import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import type { AdminCategory } from '../../api/types'
import { api } from '../../api/gymshop'
import { describeAdminError } from './adminErrors'
import { AdminEmpty, AdminFeedback, AdminLoading } from './adminUi'

export function CategoriesAdmin() {
  const location = useLocation(); const [categories, setCategories] = useState<AdminCategory[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [busyId, setBusyId] = useState<number | null>(null); const toggling = useRef(false)
  useEffect(() => { let active = true; setLoading(true); setError(''); api.adminCategories().then(value => { if (active) setCategories(value) }).catch(value => { if (active) setError(describeAdminError(value)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [retry])
  const visible = useMemo(() => categories.filter(item => { const term = search.trim().toLowerCase(); return (!term || item.name.toLowerCase().includes(term) || item.slug.toLowerCase().includes(term)) && (status === 'all' || item.isActive === (status === 'active')) }), [categories, search, status])
  const changeStatus = async (category: AdminCategory) => { if (toggling.current || !confirm(`¿Querés ${category.isActive ? 'desactivar' : 'activar'} “${category.name}”?`)) return; toggling.current = true; setBusyId(category.id); setError(''); try { await api.setCategoryStatus(category.id, !category.isActive); setCategories(current => current.map(item => item.id === category.id ? { ...item, isActive: !item.isActive } : item)) } catch (value) { setError(describeAdminError(value)) } finally { toggling.current = false; setBusyId(null) } }
  const notice = (location.state as { categoryNotice?: string } | null)?.categoryNotice
  return <section className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow">CATÁLOGO</p><h1>Categorías</h1><p>Administrá la organización visible de la tienda.</p></div><Link className="primary link-button" to="/admin/categorias/nueva">Nueva categoría</Link></div>
    <AdminFeedback error={error} success={notice} />
    <div className="admin-filters category-filters"><label className="admin-search">Buscar<input aria-label="Buscar categorías" value={search} onChange={event => setSearch(event.target.value)} placeholder="Nombre o slug" /></label><label>Estado<select aria-label="Filtrar por estado" value={status} onChange={event => setStatus(event.target.value)}><option value="all">Todas</option><option value="active">Activas</option><option value="inactive">Inactivas</option></select></label>{(search || status !== 'all') && <button type="button" onClick={() => { setSearch(''); setStatus('all') }}>Limpiar</button>}</div>
    {loading ? <AdminLoading label="Cargando categorías…" /> : error && categories.length === 0 ? <AdminEmpty>No se pudo cargar el listado. <button onClick={() => setRetry(value => value + 1)}>Reintentar</button></AdminEmpty> : categories.length === 0 ? <AdminEmpty>Todavía no hay categorías.</AdminEmpty> : visible.length === 0 ? <AdminEmpty>No hay resultados para los filtros aplicados.</AdminEmpty> : <div className="category-table"><div className="category-row category-header"><span>Nombre</span><span>Descripción</span><span>Orden</span><span>Productos</span><span>Estado</span><span>Acciones</span></div>{visible.map(category => <article className="category-row" key={category.id}><div><strong>{category.name}</strong><small>{category.slug}</small></div><span data-label="Descripción">{category.description || 'Sin descripción'}</span><span data-label="Orden">{category.displayOrder}</span><span data-label="Productos">{category.productCount}</span><span data-label="Estado" className={category.isActive ? 'status active' : 'status inactive'}>{category.isActive ? 'Activa' : 'Inactiva'}</span><div className="category-actions"><Link to={`/admin/categorias/${category.id}/editar`}>Editar</Link><button type="button" disabled={busyId === category.id} onClick={() => void changeStatus(category)}>{busyId === category.id ? 'Procesando…' : category.isActive ? 'Desactivar' : 'Activar'}</button></div></article>)}</div>}
  </section>
}
