import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'

const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
const categories = [
  { id: 1, name: 'Fuerza', slug: 'fuerza', description: 'Pesas', displayOrder: 1, isActive: true, productCount: 3 },
  { id: 2, name: 'Movilidad', slug: 'movilidad', description: null, displayOrder: 2, isActive: false, productCount: 1 },
]
function signIn(role: 'Admin' | 'SuperAdmin' | 'User' = 'Admin') { localStorage.setItem('gymshop.token', 'jwt'); localStorage.setItem('gymshop.user', JSON.stringify({ id: 1, email: 'admin@gym.com', name: role, role })) }
function apiMock(input: RequestInfo | URL, init?: RequestInit) { const url = String(input); if (url.includes('/api/cart')) return json({ id: 1, userId: 1, total: 0, items: [] }); if (url.endsWith('/api/categories/admin')) return json(categories); if (url.endsWith('/api/categories/1/status') && init?.method === 'PATCH') return json(null); if (url.endsWith('/api/categories') && init?.method === 'POST') return json({ ...categories[0], id: 3, name: 'Cardio', slug: 'cardio' }, 201); return json([]) }

describe('administración de categorías', () => {
  beforeEach(() => { localStorage.clear(); window.history.replaceState(null, '', '/'); vi.restoreAllMocks() })
  it.each(['Admin', 'SuperAdmin'] as const)('%s consulta activas e inactivas', async role => { signIn(role); window.history.replaceState(null, '', '/admin/categorias'); vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); expect(await screen.findByText('Fuerza')).toBeInTheDocument(); expect(screen.getByText('Movilidad')).toBeInTheDocument() })
  it('filtra por búsqueda y estado', async () => { signIn(); window.history.replaceState(null, '', '/admin/categorias'); vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); await screen.findByText('Fuerza'); await userEvent.type(screen.getByLabelText('Buscar categorías'), 'movi'); expect(screen.queryByText('Fuerza')).not.toBeInTheDocument(); await userEvent.clear(screen.getByLabelText('Buscar categorías')); await userEvent.selectOptions(screen.getByLabelText('Filtrar por estado'), 'inactive'); expect(screen.getByText('Movilidad')).toBeInTheDocument(); expect(screen.queryByText('Fuerza')).not.toBeInTheDocument() })
  it('confirma y evita duplicar un cambio de estado', async () => { signIn(); window.history.replaceState(null, '', '/admin/categorias'); vi.spyOn(window, 'confirm').mockReturnValue(true); const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); await userEvent.click(await screen.findByRole('button', { name: 'Desactivar' })); await waitFor(() => expect(fetchMock.mock.calls.filter(([input, init]) => String(input).endsWith('/api/categories/1/status') && (init as RequestInit).method === 'PATCH')).toHaveLength(1)); expect(screen.getAllByText('Inactiva')).toHaveLength(2) })
  it('rechaza un id inválido sin consultar la API', async () => { signIn(); window.history.replaceState(null, '', '/admin/categorias/no/editar'); const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); expect(await screen.findByText('Categoría no encontrada.')).toBeInTheDocument(); expect(fetchMock.mock.calls.some(([input]) => String(input).includes('/api/categories/no'))).toBe(false) })
  it('valida antes de crear y envía una sola vez', async () => { signIn(); window.history.replaceState(null, '', '/admin/categorias/nueva'); const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); await userEvent.click(screen.getByRole('button', { name: 'Crear categoría' })); expect(await screen.findByText('Ingresá un nombre.')).toBeInTheDocument(); expect(fetchMock.mock.calls.some(([, init]) => (init as RequestInit | undefined)?.method === 'POST')).toBe(false); await userEvent.type(screen.getByLabelText('Nombre'), 'Cardio'); await userEvent.click(screen.getByRole('button', { name: 'Crear categoría' })); await waitFor(() => expect(window.location.pathname).toBe('/admin/categorias')); expect(fetchMock.mock.calls.filter(([, init]) => (init as RequestInit | undefined)?.method === 'POST')).toHaveLength(1) })
  it('envía el color seleccionado al crear una categoría', async () => { signIn(); window.history.replaceState(null, '', '/admin/categorias/nueva'); const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(apiMock); render(<App />); await userEvent.type(screen.getByLabelText('Nombre'), 'Cardio'); await userEvent.selectOptions(screen.getByLabelText('Color de categoría'), '#57d7ff'); await userEvent.click(screen.getByRole('button', { name: 'Crear categoría' })); await waitFor(() => expect(window.location.pathname).toBe('/admin/categorias')); const request = fetchMock.mock.calls.find(([, init]) => (init as RequestInit | undefined)?.method === 'POST'); expect(JSON.parse(String(request?.[1]?.body)).color).toBe('#57d7ff') })
})
