import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ApiError } from '../../api/client'
import { api } from '../../api/gymshop'
import type { AdminCategory } from '../../api/types'
import { describeAdminError } from './adminErrors'
import { AdminEmpty, AdminFeedback, AdminLoading } from './adminUi'
import { CategoryForm } from './CategoryForm'
import { categoryToFormValues, emptyCategoryValues, toCategoryInput, type CategoryFormErrors, type CategoryFormValues } from './categoryFormValidation'

export function CategoryEditorPage({ mode }: { mode: 'create' | 'edit' }) {
  const { categoryId } = useParams(); const navigate = useNavigate(); const id = Number(categoryId); const validId = Number.isInteger(id) && id > 0; const [category, setCategory] = useState<AdminCategory | null>(null); const [loading, setLoading] = useState(mode === 'edit'); const [notFound, setNotFound] = useState(false); const [loadError, setLoadError] = useState(''); const [submitError, setSubmitError] = useState(''); const [fieldErrors, setFieldErrors] = useState<CategoryFormErrors>({}); const [busy, setBusy] = useState(false); const [retry, setRetry] = useState(0); const submitting = useRef(false)
  useEffect(() => { if (mode === 'create') return; if (!validId) { setNotFound(true); setLoading(false); return } let active = true; setLoading(true); setLoadError(''); api.adminCategory(id).then(value => { if (active) setCategory(value) }).catch(value => { if (!active) return; if (value instanceof ApiError && value.status === 404) setNotFound(true); else setLoadError(describeAdminError(value)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, mode, retry, validId])
  const save = async (values: CategoryFormValues) => { if (submitting.current) return; submitting.current = true; setBusy(true); setSubmitError(''); setFieldErrors({}); try { const saved = mode === 'create' ? await api.createCategory(toCategoryInput(values)) : await api.updateCategory(id, toCategoryInput(values)); navigate('/admin/categorias', { replace: true, state: { categoryNotice: `${saved.name} fue ${mode === 'create' ? 'creada' : 'actualizada'} correctamente.` } }) } catch (value) { if (value instanceof ApiError && /nombre/i.test(value.message)) setFieldErrors({ name: value.message }); else if (value instanceof ApiError && /slug/i.test(value.message)) setFieldErrors({ slug: value.message }); else setSubmitError(describeAdminError(value)); submitting.current = false; setBusy(false) } }
  return <section className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow">CATÁLOGO</p><h1>{mode === 'create' ? 'Nueva categoría' : 'Editar categoría'}</h1><p>El slug se genera desde el nombre y podés ajustarlo antes de guardar.</p></div><Link to="/admin/categorias">← Volver al listado</Link></div><AdminFeedback error={loadError || submitError} />{loading ? <AdminLoading label="Cargando categoría…" /> : notFound ? <AdminEmpty>Categoría no encontrada.</AdminEmpty> : loadError ? <AdminEmpty>No se pudo preparar el formulario. <button onClick={() => setRetry(value => value + 1)}>Reintentar</button></AdminEmpty> : mode === 'edit' && !category ? <AdminEmpty>Categoría no encontrada.</AdminEmpty> : <CategoryForm mode={mode} values={category ? categoryToFormValues(category) : emptyCategoryValues()} busy={busy} serverErrors={fieldErrors} onSubmit={values => void save(values)} />}</section>
}
