import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'

const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
const users = [{ id: 2, name: 'Ana Cliente', email: 'ana@test.com', role: 'User', isActive: true, createdAt: '2026-01-01T00:00:00Z' }]
function signIn() { localStorage.setItem('gymshop.token', 'jwt'); localStorage.setItem('gymshop.user', JSON.stringify({ id: 1, email: 'root@test.com', name: 'Root', role: 'SuperAdmin' })) }
function mockApi(input: RequestInfo | URL, init?: RequestInit) {
  const url = String(input)
  if (url.includes('/api/cart')) return json({ id: 1, userId: 1, total: 0, items: [] })
  if (url.includes('/api/users/2') && (!init?.method || init.method === 'GET')) return json({ ...users[0], orderCount: 1, totalPurchased: 100, lastOrderAt: '2026-02-01T00:00:00Z', ordersTotal: 1, ordersPageSize: 10, recentOrders: [{ id: 9, createdAt: '2026-02-01T00:00:00Z', total: 100, status: 'Paid' }] })
  if (url.includes('/api/orders?')) return json({ items: [{ id: 9, userId: 2, userEmail: 'ana@test.com', userName: 'Ana Cliente', createdAt: '2026-02-01T00:00:00Z', total: 100, status: 'Paid', updatedAt: null, lastPaymentStatus: 'Approved', lastPaymentId: 1 }], page: 1, pageSize: 20, totalItems: 1, totalPages: 1 })
  if (url.includes('/api/users') && init?.method === 'POST') return json({ ...users[0], id: 3, name: 'Nuevo' }, 201)
  if (url.includes('/api/users')) return json({ items: users, page: url.includes('page=2') ? 2 : 1, pageSize: 20, totalItems: 21, totalPages: 2 })
  return json({})
}

describe('administración de usuarios', () => {
  beforeEach(() => { signIn(); window.history.replaceState(null, '', '/admin/usuarios'); vi.restoreAllMocks() })
  it('conecta búsqueda, filtros y paginación al backend', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(mockApi); render(<App />); await screen.findByText('Ana Cliente'); await userEvent.type(screen.getByLabelText('Nombre o email'), 'ana'); await userEvent.selectOptions(screen.getByLabelText('Tipo / rol'), 'User'); await userEvent.click(screen.getByRole('button', { name: 'Buscar' })); await waitFor(() => expect(fetchMock.mock.calls.some(([input]) => String(input).includes('search=ana') && String(input).includes('role=User'))).toBe(true)); await userEvent.click(screen.getByRole('button', { name: 'Siguiente' })); await waitFor(() => expect(fetchMock.mock.calls.some(([input]) => String(input).includes('page=2'))).toBe(true)) })
  it('crea un usuario evitando doble envío', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(mockApi); render(<App />); await screen.findByText('Ana Cliente'); await userEvent.click(screen.getByRole('button', { name: 'Crear usuario' })); const dialog = screen.getByRole('dialog', { name: 'Crear usuario' }); await userEvent.type(within(dialog).getByLabelText('Nombre'), 'Nuevo'); await userEvent.type(within(dialog).getByLabelText('Email'), 'nuevo@test.com'); await userEvent.type(within(dialog).getByLabelText('Contraseña'), '123456'); await userEvent.click(within(dialog).getByRole('button', { name: 'Crear usuario' })); await waitFor(() => expect(fetchMock.mock.calls.filter(([, init]) => init?.method === 'POST')).toHaveLength(1)) })
  it('después del alta limpia filtros y refresca una sola vez sin el closure anterior', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(mockApi); render(<App />); await screen.findByText('Ana Cliente'); await userEvent.type(screen.getByLabelText('Nombre o email'), 'ana'); await userEvent.selectOptions(screen.getByLabelText('Tipo / rol'), 'Admin'); await userEvent.selectOptions(screen.getByLabelText('Estado'), 'inactive'); await userEvent.click(screen.getByRole('button', { name: 'Buscar' })); await waitFor(() => expect(fetchMock.mock.calls.some(([input]) => String(input).includes('search=ana'))).toBe(true)); const beforeCreate = fetchMock.mock.calls.length; await userEvent.click(screen.getByRole('button', { name: 'Crear usuario' })); const dialog = screen.getByRole('dialog', { name: 'Crear usuario' }); await userEvent.type(within(dialog).getByLabelText('Nombre'), 'Nuevo'); await userEvent.type(within(dialog).getByLabelText('Email'), 'nuevo@test.com'); await userEvent.type(within(dialog).getByLabelText('Contraseña'), '123456'); await userEvent.click(within(dialog).getByRole('button', { name: 'Crear usuario' })); await waitFor(() => expect(fetchMock.mock.calls.slice(beforeCreate).filter(([input, init]) => String(input).includes('/api/users?') && (!init?.method || init.method === 'GET'))).toHaveLength(1)); const refreshUrl = String(fetchMock.mock.calls.slice(beforeCreate).find(([input, init]) => String(input).includes('/api/users?') && (!init?.method || init.method === 'GET'))![0]); expect(refreshUrl).not.toContain('search='); expect(refreshUrl).not.toContain('role='); expect(refreshUrl).not.toContain('isActive=') })
  it('muestra detalle, métricas e historial', async () => { vi.spyOn(globalThis, 'fetch').mockImplementation(mockApi); render(<App />); await userEvent.click(await screen.findByRole('button', { name: 'Detalle' })); const detail = await screen.findByRole('dialog', { name: 'Detalle de usuario' }); expect(within(detail).getByText('Pedidos válidos')).toBeInTheDocument(); expect(within(detail).getByText('Pedido #9')).toBeInTheDocument() })
  it('navega desde un usuario al pedido y aplica el query string compartible', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(mockApi); render(<App />); await userEvent.click(await screen.findByRole('button', { name: 'Detalle' })); await userEvent.click(await screen.findByText('Pedido #9')); await waitFor(() => expect(window.location.pathname).toBe('/admin/pedidos')); expect(window.location.search).toBe('?search=%239'); await waitFor(() => expect(fetchMock.mock.calls.some(([input]) => String(input).includes('/api/orders?') && String(input).includes('search=%239'))).toBe(true)); expect(screen.getByRole('searchbox', { name: 'Buscar' })).toHaveValue('#9') })
  it('muestra errores claros de seguridad', async () => { vi.spyOn(window, 'confirm').mockReturnValue(true); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => String(input).includes('/status') && init?.method === 'PATCH' ? json({ message: 'No podes desactivar tu propio usuario.' }, 409) : mockApi(input, init)); render(<App />); await userEvent.click(await screen.findByRole('button', { name: 'Desactivar' })); expect(await screen.findByText('No podes desactivar tu propio usuario.')).toBeInTheDocument() })
})
